# -*- coding: utf-8 -*-
"""Example1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sof_uUhj81-XMoIo1HV6jux32K6EXt5R
"""

# Solvce for the area of a rectangle

class Rectangle:
  def __init__(self, width, height):
    self.width = width
    self.height = height

  def Area(self):
    return self.width * self.height

  def Display(self):
    print(f"The Area is of the Rectangle is {self.Area()}")

x = int(input("Enter Rectangle's Width: "))
y = int(input("Enter Rectangle's Heigth: "))

person = Rectangle(x, y)
person.Display()