# -*- coding: utf-8 -*-
"""Practice Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NPhNZV-QBbxK7CLHbOmgG__UjxDEwo4d
"""

# Practice Problem

test_scores = [26, 49, 98, 87, 62, 75]
even = 0

for score in test_scores:
  if score % 2 == 0:
    even += score
  else:
    pass

print(even)